spring.application.name=demo

server.port=8090


spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.ai.openai.base-url: http://127.0.0.1:1234
spring.ai.openai.api-key: dummy-api-key
spring.ai.openai.chat.options.model: qwen/qwen3.5-35b-a3b